# This is a basic workflow to help you get started with Actions

name: Release PAC Rules

# Controls when the workflow will run
on:
  push:
    paths:
      - 'pac.txt'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload pac.txt
        uses: actions/upload-artifact@v2
        with:
          name: pac.txt
          path: pac.txt
